---
- name: Vars block
  vars:
    rpm_file: "{{ apps_tmpdir.path }}/{{ item.key }}.rpm"
  when: item.key not in ansible_facts.packages or apps_upgrade | bool
  block:
    - name: "Download RPM file for {{ item.key }}"
      ansible.builtin.get_url:
        url: "{{ item.value }}"
        dest: "{{ rpm_file }}"
        mode: "0644"

    - name: "Install RPM for {{ item.key }}"
      ansible.builtin.dnf:
        name: "{{ rpm_file }}"
        state: present
        disable_gpg_check: true
