---
ssh_authorized_keys_extra:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMpV1NruIlhslQT56n+Gzr63c55RcumQKUUAiZnYDTC

ssh_identity_keys_extra:
  grnoc: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8Xxm9Z8N7F9zDd9WiY0WE3Uv7ezeKavo90dfwswbsL
  i2: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8Xxm9Z8N7F9zDd9WiY0WE3Uv7ezeKavo90dfwswbsL
  jdratlif: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMpV1NruIlhslQT56n+Gzr63c55RcumQKUUAiZnYDTC
  noaa: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+loEqnuYPbHD9SiasW0MTs19EJKSLbd+pwYhEdcRgmz2dESvLhpn3tH2O2eYMIzLQoVCMT8KpEwmhpFRuJ5w9Cxoqe1ReqLbVtOWlVD/BLPIzaUQhQa0+TSM2ETMXgkmGa4ARGrJVCzCQH0+z6rGX6OvWTQUEFDG0QM8ZdON+9Py6P3ZwrRDhSOobclkov7KDxqUi5SM3mjdBTdaHigNaGg7+N/koXakOwTd7Bd4PBtOWVhsqa87uOaOGXyRTeOpkE1XzFlhGOsMvd1SwN9U/DrJyazgwbJjhqXDuhOcPYFgWv0nGPX4uplDffviij6c+I9i1sMHlmDCbIU6jxKXh
  nwave: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8Xxm9Z8N7F9zDd9WiY0WE3Uv7ezeKavo90dfwswbsL
  scinet: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8Xxm9Z8N7F9zDd9WiY0WE3Uv7ezeKavo90dfwswbsL
  scinet-piv: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7gLhqbdNlK8OE4HujfiUHVSzqZPh/zJmjoWzA4V0O8cuDXIUiIDwvSwqBV1NB1RBoPF45X+nntdONzShHbevn8lNpAitHGeDADz4WR0RW6UJ5pW3rzJlacWYrw0lYjl32uDACWsik/Iz2gXx7X/sxKHhIrQrd8+X6UOg2CUHJ6N4AfQQ8lH6PYsr8w4sa4KEnJv+kGTAbtpmaIBIJgkMmEDtfllFIbW76x/Ax0ZsIujnhSi5SMqi4i+2tj6qeBaoy/LmsfBGXmioxDh4TIx5SVausO5WyhTJFm0m8b8PRVz3yc2TbSyh7/HlfdAl5c/YqvO/q1Y4sqIcp1OROcDAP
  technoplaza: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEwdDfiqveE9xwaJ21C/GOeheGk4OuczJXi11t1dmELG
  xaiver: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBc+bQFdinbcO0eHrnxfLM+OroTUOt3RKHkTbrh6hNfm

ssh_common_options_extra:
  IdentitiesOnly: "yes"
  IdentityAgent: ~/.1password/agent.sock
  ControlMaster: auto
  ControlPath: ~/.ssh/cp-%r@%h:%p
  ControlPersist: 5m

ssh_host_options_extra:
  jdratlif-dev8.bldc.grnoc.iu.edu: &devbox
    ForwardAgent: "yes"
    IdentityFile: ~/.ssh/jdratlif.pub
    RemoteForward:
      - "*:1080 localhost:1080"
      - "*:1081 localhost:1081"
      - "*:1082 localhost:1082"
      - "*:1083 localhost:1083"
  jdratlif-dev8.ctc.grnoc.iu.edu:
    <<: *devbox
  sandbox.grnoc.iu.edu: {}
  puppet7.grnoc.iu.edu:
    IdentityFile: ~/.ssh/jdratlif.pub
  puppet7.bldc.nwave.noaa.gov: {}
  pangolin16: &laptop-hosts
    IdentityFile: ~/.ssh/jdratlif.pub
  asahi:
    <<: *laptop-hosts
  htpc: &homelab-hosts
    IdentityFile: ~/.ssh/xaiver.pub
  pve:
    <<: *homelab-hosts
  leap: &grnoc-bastion
    Hostname: leap.grnoc.iu.edu
  skip:
    Hostname: skip.grnoc.iu.edu
  jump:
    Hostname: jump.grnoc.iu.edu
  grnoc:
    <<: *grnoc-bastion
    DynamicForward: "*:1080"
    IdentityFile: ~/.ssh/grnoc.pub
  i2-bldc: &i2-bastion
    Hostname: bastion.bldc.net.internet2.edu
  i2-ctc:
    Hostname: bastion.ctc.net.internet2.edu
  i2:
    <<: *i2-bastion
    DynamicForward: "*:1082"
    IdentityFile: ~/.ssh/i2.pub
  noaa-bldc: &noaa-bastion
    Hostname: bastion.bldc.nwave.noaa.gov
  noaa-ctc:
    Hostname: bastion.ctc.nwave.noaa.gov
  noaa-boul:
    Hostname: bastion.boul.nwave.noaa.gov
  noaa:
    <<: *noaa-bastion
    DynamicForward: "*:1081"
  scinet-bldc: &scinet-bastion
    Hostname: bastion.bldc.scinet.usda.gov
  scinet-ctc:
    Hostname: bastion.ctc.scinet.usda.gov
  scinet:
    <<: *scinet-bastion
    DynamicForward: "*:1083"

ssh_match_options_extra:
  "originalhost *.grnoc.iu.edu,*.globalnoc.iu.edu,!leap.grnoc.iu.edu,!skip.grnoc.iu.edu,!jump.grnoc.iu.edu":
    ProxyJump: grnoc
    IdentityFile: ~/.ssh/grnoc.pub
  "originalhost *.net.internet2.edu,!bastion.bldc.net.internet2.edu,!bastion.ctc.net.internet2.edu":
    ProxyJump: i2
    IdentityFile: ~/.ssh/i2.pub
  "originalhost *.nwave.noaa.gov,*.alaskaix.net,!bastion.*.nwave.noaa.gov":
    ProxyJump: nwave
    IdentityFile: ~/.ssh/noaa.pub
  "originalhost *.scinet.usda.gov,!bastion.*.scinet.usda.gov":
    ProxyJump: scinet
    IdentityFile: ~/.ssh/scinet.pub
  "host bastion.*.nwave.noaa.gov": &pkcs11-match
    IdentityFile: ~/.ssh/noaa.pub
    PKCS11Provider: /usr/lib64/pkcs11/opensc-pkcs11.so
  "host bastion.*.scinet.usda.gov,bastion.*.nwave.noaa.gov":
    <<: *pkcs11-match
    IdentityFile: ~/.ssh/scinet-piv.pub
