- name: Tags block
  tags: [apps_packages_repo]
  block:
    - name: Install third-party repos
      ansible.builtin.get_url:
        url: "{{ item.value }}"
        dest: "/etc/yum.repos.d/{{ item.key }}.repo"
        mode: "0644"
      loop: "{{ apps_repos_final }}"

    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ apps_packages_final }}"
        state: "{{ 'latest' if apps_upgrade | bool else 'present' }}"
        update_only: "{{ apps_upgrade | bool }}"
        allowerasing: true

- name: Tags block
  tags: [apps_packages_rpms]
  block:
    - name: Create temp dir for RPM packages
      ansible.builtin.tempfile:
        state: directory
      register: apps_tmpdir

    - name: Gather facts about installed packages
      ansible.builtin.package_facts:

    - name: Install RPM packages
      ansible.builtin.include_tasks: includes/rpm_package.yml
      loop: "{{ apps_rpms_final }}"
  always:
    - name: Remove tempdir for RPM downloads
      ansible.builtin.file:
        state: absent
        path: "{{ apps_tmpdir.path }}"
