---
bash_aliases_final: |
  {{
    bash_aliases
    | combine(bash_aliases_extra)
    | dict2items
    | rejectattr('key', 'in', bash_aliases_skip)
    | sort(attribute='key')
  }}

bash_aliases_presets:
  ls: ls --color=auto
  ll: ls -l --color=auto

bash_environment_final: |
  {{
    bash_environment
    | combine(bash_environment_extra)
    | dict2items
    | rejectattr('key', 'in', bash_environment_skip)
    | sort(attribute='key')
  }}

bash_functions_final: |
  {{
    bash_functions
    | combine(bash_functions_extra)
    | dict2items
    | rejectattr('key', 'in', bash_functions_skip)
    | sort(attribute='key')
  }}

# Sorting or using filters could change the order
# Using custom logic to preserve order while removing duplicates and skipped paths
bash_paths_final: |
  {%- set seen = [] -%}
  {%- set result = [] -%}
  {%- for path in (bash_paths + bash_paths_extra) -%}
    {%- if path not in bash_paths_skip and path not in seen -%}
      {%- set _ = seen.append(path) -%}
      {%- set _ = result.append(path) -%}
    {%- endif -%}
  {%- endfor -%}
  {{ result }}

bash_paths_presets: [~/.local/bin, ~/bin]

bash_shell_options_final: |
  {{
    bash_shell_options
    | union(bash_shell_options_extra)
    | difference(bash_shell_options_skip)
    | sort
  }}

bash_sources_final: |
  {{
    bash_sources
    | union(bash_sources_extra)
    | difference(bash_sources_skip)
    | sort
  }}

bash_sources_presets: [/usr/share/bash-completion/bash_completion]
bash_templates: [bash_profile, bashrc]
