# Generated by Anaconda 42.27.12
# Generated by pykickstart v3.62
#version=DEVEL

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=link --ipv6=auto --activate
network  --hostname=fedora-ks

%packages
# base install
@core
qemu-guest-agent
python3-dnf
python3-libdnf5
%end

# partitioning
ignoredisk --only-use=sda
autopart
zerombr
clearpart --all --initlabel

# System timezone
timezone America/Indiana/Indianapolis --utc

#Root password
rootpw --lock
user --groups=wheel --name=proxmox --password=$y$j9T$l5cbl5rwbGB8n1MjGGbO1/$PMGb2YlzrNxj9Jh3ARirOtetUjdpoV7LOiSgniRqRXB --iscrypted --gecos="Proxmox User"
