---
- name: Make ssh config directory
  ansible.builtin.file:
    path: "{{ user_info.home }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"
  tags: [dotfiles_ssh_configs, dotfiles_ssh_identity]

- name: Template ssh configs
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ user_info.home }}/.ssh/{{ item }}"
    backup: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop: "{{ ssh_config_templates }}"
  tags: dotfiles_ssh_configs

- name: Add ssh identity files
  ansible.builtin.copy:
    content: |
      {{ item.value }}
    dest: "{{ user_info.home }}/.ssh/{{ item.key }}.pub"
    backup: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop: "{{ ssh_identity_keys_final }}"
  tags: dotfiles_ssh_identity
