---
- name: Tags block
  tags: [apps_special_joplin]
  block:
    - name: Install fuse-libs for AppImage
      ansible.builtin.package:
        name: fuse-libs
        state: present
      become: true

    - name: Check is joplin is installed
      ansible.builtin.stat:
        path: "{{ user_info.home }}/.joplin/Joplin.AppImage"
        get_checksum: false
        get_attributes: false
      register: apps_stat

    - name: Install joplin
      ansible.builtin.import_tasks: includes/shell_install.yml
      vars:
        apps_url: https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
        apps_shell: /bin/bash
      when: not apps_stat.stat.exists or apps_upgrade | bool
