- name: Tags block
  tags: [apps_special_uv]
  block:
    - name: Check if uv is installed
      ansible.builtin.stat:
        path: /usr/local/bin/uv
        get_attributes: false
        get_checksum: false
      register: apps_stat

    - name: When block
      vars:
        uv_tarball: "{{ apps_tmpdir.path }}/uv.tar.gz"
      when: not apps_stat.stat.exists or apps_upgrade | bool
      block:
        - name: Install required packages to extract archive
          ansible.builtin.package:
            name: tar
            state: present
          become: true

        - name: Get uv package info from GitHub API
          ansible.builtin.uri:
            url: https://api.github.com/repos/astral-sh/uv/releases/latest
            return_content: true
          register: apps_uv_info

        - name: Download uv
          ansible.builtin.get_url:
            url: "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-x86_64-unknown-linux-gnu.tar.gz"
            dest: "{{ uv_tarball }}"
            mode: "0644"
          vars:
            uv_version: "{{ apps_uv_info.json.tag_name }}"

        - name: Extract uv tarball
          ansible.builtin.unarchive:
            src: "{{ uv_tarball }}"
            dest: "{{ apps_tmpdir.path }}"
            remote_src: true

        - name: Copy uv binary to /usr/local/bin
          ansible.builtin.copy:
            src: "{{ apps_tmpdir.path }}/uv-x86_64-unknown-linux-gnu/uv"
            dest: /usr/local/bin/
            mode: "0755"
            remote_src: true
          become: true
